name: audio-transcription
runtime: nodejs
description: Google Cloud Function for audio transcription
scripts:
  postup:
    - pulumi stack output functionUrl | sed "s/^/export default '/" | sed "s/$/'/" > ../website/src/stack-output.ts
